name: Flutter CI/CD with Firebase Distribution

on:
  push:
    branches: [ main ]

jobs:
  # build-android:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.29.2'
  #       channel: 'stable'
    
  #   - name: Install dependencies
  #     run: flutter pub get
    
  #   - name: Build APK
  #     run: flutter build apk 
  #     env:
  #       ANDROID_SDK_ROOT: /usr/lib/android-sdk
        
  #   - name: Upload APK to Firebase App Distribution
  #     uses: wzieba/Firebase-Distribution-Github-Action@v1
  #     with:
  #       appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
  #       token: ${{ secrets.FIREBASE_CLI_TOKEN }}
  #       groups: testers  # or your preferred group
  #       file: build/app/outputs/flutter-apk/app-release.apk
  #       releaseNotes: "Automatic build from GitHub Actions (Commit: ${{ github.sha }})"

  #   - name: Upload APK as artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: app-release.apk
  #       path: build/app/outputs/flutter-apk/app-release.apk
  #       retention-days: 7


  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Install Apple certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Install provisioning profile (manual)
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          # Decode and save the provisioning profile
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > /tmp/profile.mobileprovision
          # Try to extract UUID using different methods
          echo "Attempting to extract UUID from provisioning profile..."
          if command -v security >/dev/null 2>&1; then
            UUID=$(security cms -D -i /tmp/profile.mobileprovision 2>/dev/null | plutil -extract UUID raw - 2>/dev/null || echo "")
          fi
          if [ -z "$UUID" ]; then
            echo "Security method failed, trying openssl..."
            UUID=$(openssl smime -verify -inform DER -in /tmp/profile.mobileprovision -noverify 2>/dev/null | plutil -extract UUID raw - 2>/dev/null || echo "")
          fi
          if [ -z "$UUID" ]; then
            echo "UUID extraction failed, using timestamp-based filename..."
            UUID="profile-$(date +%s)"
          fi
          echo "Using filename: $UUID.mobileprovision"
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
          # List installed profiles for verification
          echo "Installed profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          # Try to verify the profile contains our bundle identifier
          echo "Checking profile content..."
          if security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision 2>/dev/null | grep -q "com.example.flutterRiverpodTutorial"; then
            echo "✅ Bundle ID found in provisioning profile"
          else
            echo "⚠️  Bundle ID not found in profile, but continuing..."
          fi
      - name: Build IPA
        run: |
          echo "Starting Flutter IPA build..."
          echo "=== Build Environment Info ==="
          flutter --version
          xcodebuild -version
          
          flutter build ipa \
            --dart-define=APP_ENV=production \
            --export-options-plist=ios/ExportOptions.plist \
            --verbose \
            --codesign 2>&1 | tee flutter_build.log
          
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          echo "Flutter build exit code: $BUILD_EXIT_CODE"
          
          echo "=== Flutter build log tail ==="
          tail -50 flutter_build.log
          
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "❌ Flutter build failed with exit code $BUILD_EXIT_CODE"
            echo "=== Full build log ==="
            cat flutter_build.log
            exit $BUILD_EXIT_CODE
          else
            echo "✅ Flutter build completed successfully"
          fi
      - name: Verify IPA file
        run: |
          echo "Checking for IPA files..."
          
          # Check the most likely location first
          if [ -f "build/ios/ipa/flutter_riverpod_tutorial.ipa" ]; then
            echo "✅ IPA file found at expected location: build/ios/ipa/flutter_riverpod_tutorial.ipa"
            IPA_FILE="build/ios/ipa/flutter_riverpod_tutorial.ipa"
          else
            echo "=== Searching for IPA files in all locations ==="
            IPA_FILE=$(find . -name "*.ipa" -type f 2>/dev/null | head -1)
            
            if [ -n "$IPA_FILE" ]; then
              echo "✅ IPA file found at: $IPA_FILE"
            else
              echo "❌ No IPA file found anywhere"
              echo "=== Debugging: Checking build directory structure ==="
              find build -type f 2>/dev/null | grep -E "\.(ipa|xcarchive)$" || echo "No IPA or archive files found"
              
              echo "=== Checking for build directories ==="
              ls -la build/ios/ 2>/dev/null || echo "build/ios/ directory does not exist"
              exit 1
            fi
          fi
          
          # Verify the IPA file is valid
          echo "=== IPA File Details ==="
          ls -lh "$IPA_FILE"
          file "$IPA_FILE"
          
          # Set environment variable for next steps
          echo "IPA_PATH=$IPA_FILE" >> $GITHUB_ENV
          echo "✅ IPA verification completed successfully"
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ${{ env.IPA_PATH }}
          retention-days: 7

  distribute-ios:
    needs: build-ios
    runs-on: ubuntu-latest
    steps:
      - name: Download IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-app
          path: ./
      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la ./
          
          # The IPA should be named flutter_riverpod_tutorial.ipa based on your project
          if [ -f "flutter_riverpod_tutorial.ipa" ]; then
            echo "✅ Found flutter_riverpod_tutorial.ipa"
            mv flutter_riverpod_tutorial.ipa app-release.ipa
          else
            # Fallback: look for any IPA file
            IPA_FILES=(*.ipa)
            if [ -f "${IPA_FILES[0]}" ]; then
              echo "✅ Found IPA file: ${IPA_FILES[0]}, renaming to app-release.ipa"
              mv "${IPA_FILES[0]}" app-release.ipa
            else
              echo "❌ No IPA file found in downloaded artifacts"
              echo "Available files:"
              ls -la ./
              exit 1
            fi
          fi
          
          echo "Final file check:"
          ls -la ./app-release.ipa
          file app-release.ipa
      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: testers
          file: app-release.ipa
          releaseNotes: "Automatic build from GitHub Actions (Commit: ${{ github.sha }})"
