name: Flutter CI/CD with Firebase Distribution

on:
  push:
    branches: [ main ]

jobs:
  # build-android:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.29.2'
  #       channel: 'stable'
    
  #   - name: Install dependencies
  #     run: flutter pub get
    
  #   - name: Build APK
  #     run: flutter build apk 
  #     env:
  #       ANDROID_SDK_ROOT: /usr/lib/android-sdk
        
  #   - name: Upload APK to Firebase App Distribution
  #     uses: wzieba/Firebase-Distribution-Github-Action@v1
  #     with:
  #       appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
  #       token: ${{ secrets.FIREBASE_CLI_TOKEN }}
  #       groups: testers  # or your preferred group
  #       file: build/app/outputs/flutter-apk/app-release.apk
  #       releaseNotes: "Automatic build from GitHub Actions (Commit: ${{ github.sha }})"

  #   - name: Upload APK as artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: app-release.apk
  #       path: build/app/outputs/flutter-apk/app-release.apk
  #       retention-days: 7


  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Setup CocoaPods
        run: |
          cd ios
          echo "=== CocoaPods Setup ==="
          pod --version
          echo "Cleaning previous pod installation..."
          pod deintegrate || echo "No previous pod installation found"
          echo "Installing pods..."
          # Suppress the CocoaPods configuration warning (it's cosmetic)
          pod install --repo-update 2>&1 | grep -v "CocoaPods did not set the base configuration" || true
          echo "✅ CocoaPods setup completed"
      - name: Install Apple certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Install provisioning profile (manual)
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          # Decode and save the provisioning profile
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > /tmp/profile.mobileprovision
          # Try to extract UUID using different methods
          echo "Attempting to extract UUID from provisioning profile..."
          if command -v security >/dev/null 2>&1; then
            UUID=$(security cms -D -i /tmp/profile.mobileprovision 2>/dev/null | plutil -extract UUID raw - 2>/dev/null || echo "")
          fi
          if [ -z "$UUID" ]; then
            echo "Security method failed, trying openssl..."
            UUID=$(openssl smime -verify -inform DER -in /tmp/profile.mobileprovision -noverify 2>/dev/null | plutil -extract UUID raw - 2>/dev/null || echo "")
          fi
          if [ -z "$UUID" ]; then
            echo "UUID extraction failed, using timestamp-based filename..."
            UUID="profile-$(date +%s)"
          fi
          echo "Using filename: $UUID.mobileprovision"
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
          # List installed profiles for verification
          echo "Installed profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          # Try to verify the profile contains our bundle identifier
          echo "Checking profile content..."
          if security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision 2>/dev/null | grep -q "com.example.flutterRiverpodTutorial"; then
            echo "✅ Bundle ID found in provisioning profile"
          else
            echo "⚠️  Bundle ID not found in profile, but continuing..."
          fi
      - name: Verify code signing setup
        run: |
          echo "=== Verifying Certificates ==="
          security find-identity -v -p codesigning
          echo "=== Verifying Provisioning Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "=== Profile Details ==="
          for profile in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            if [ -f "$profile" ]; then
              echo "Profile: $(basename "$profile")"
              security cms -D -i "$profile" 2>/dev/null | plutil -extract Name raw - 2>/dev/null || echo "Could not extract name"
              security cms -D -i "$profile" 2>/dev/null | plutil -extract UUID raw - 2>/dev/null || echo "Could not extract UUID"
              echo "---"
            fi
          done
      - name: Build IPA
        run: |
          echo "Starting Flutter IPA build..."
          echo "=== Build Environment Info ==="
          flutter --version
          xcodebuild -version
          
          echo "=== Checking ExportOptions.plist ==="
          cat ios/ExportOptions.plist
          
          echo "=== Attempting Flutter IPA build ==="
          flutter build ipa \
            --dart-define=APP_ENV=production \
            --export-options-plist=ios/ExportOptions.plist \
            --verbose 2>&1 | tee flutter_build.log
          
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          echo "Flutter build exit code: $BUILD_EXIT_CODE"
          
          # Check what files were created regardless of exit code
          echo "=== Checking created files ==="
          find build -name "*.ipa" -o -name "*.xcarchive" 2>/dev/null | sort || echo "No IPA or archive files found"
          
          echo "=== Build log analysis ==="
          echo "Last 50 lines of build log:"
          tail -50 flutter_build.log
          
          # Look for specific error patterns
          if grep -q -i "error\|fail\|denied" flutter_build.log; then
            echo "=== Found potential errors in log ==="
            grep -i -A 2 -B 2 "error\|fail\|denied" flutter_build.log | tail -30
          fi
          
          # If flutter build ipa failed, try alternative approach
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "❌ Flutter build ipa failed, trying alternative approach..."
            
            echo "=== Trying flutter build ios without export ==="
            flutter build ios --release --no-codesign 2>&1 | tee flutter_ios_only.log
            
            IOS_EXIT_CODE=${PIPESTATUS[0]}
            if [ $IOS_EXIT_CODE -eq 0 ]; then
              echo "✅ iOS build succeeded, attempting manual archive and export..."
              
              cd ios
              echo "=== Creating archive manually ==="
              xcodebuild -workspace Runner.xcworkspace \
                -scheme Runner \
                -configuration Release \
                -archivePath build/Runner.xcarchive \
                archive \
                DEVELOPMENT_TEAM=66VPE47DN4 \
                CODE_SIGN_STYLE=Manual 2>&1 | tee ../manual_archive.log
              
              ARCHIVE_CODE=${PIPESTATUS[0]}
              if [ $ARCHIVE_CODE -eq 0 ]; then
                echo "✅ Archive created, exporting IPA..."
                xcodebuild -exportArchive \
                  -archivePath build/Runner.xcarchive \
                  -exportPath ../build/ios/ipa \
                  -exportOptionsPlist ExportOptions.plist 2>&1 | tee ../manual_export.log
                
                EXPORT_CODE=${PIPESTATUS[0]}
                cd ..
                
                if [ $EXPORT_CODE -eq 0 ]; then
                  echo "✅ Manual export succeeded!"
                else
                  echo "❌ Manual export failed with code $EXPORT_CODE"
                  cat manual_export.log
                  exit $EXPORT_CODE
                fi
              else
                echo "❌ Manual archive failed with code $ARCHIVE_CODE"
                cat manual_archive.log
                cd ..
                exit $ARCHIVE_CODE
              fi
            else
              echo "❌ iOS build also failed"
              cat flutter_ios_only.log
              exit $IOS_EXIT_CODE
            fi
          else
            echo "✅ Flutter build ipa completed successfully"
          fi
      - name: Verify IPA file
        run: |
          echo "Checking for IPA files and build artifacts..."
          
          # Check the most likely location first
          if [ -f "build/ios/ipa/flutter_riverpod_tutorial.ipa" ]; then
            echo "✅ IPA file found at expected location: build/ios/ipa/flutter_riverpod_tutorial.ipa"
            IPA_FILE="build/ios/ipa/flutter_riverpod_tutorial.ipa"
          else
            echo "=== Searching for IPA files in all locations ==="
            IPA_FILE=$(find . -name "*.ipa" -type f 2>/dev/null | head -1)
            
            if [ -n "$IPA_FILE" ]; then
              echo "✅ IPA file found at: $IPA_FILE"
            else
              echo "❌ No IPA file found anywhere"
              echo "=== Debugging: Complete build structure ==="
              find build -type f 2>/dev/null | sort || echo "No build directory found"
              
              echo "=== Checking for archive files ==="
              find . -name "*.xcarchive" -type d 2>/dev/null | while read archive; do
                echo "Archive found: $archive"
                ls -la "$archive/Products/Applications/" 2>/dev/null || echo "No app in archive"
              done
              
              echo "=== Checking build logs for errors ==="
              if [ -f "xcodebuild_export.log" ]; then
                echo "Export log errors:"
                grep -i "error\|fail\|denied" xcodebuild_export.log | tail -10 || echo "No obvious errors in export log"
              fi
              
              if [ -f "xcodebuild_archive.log" ]; then
                echo "Archive log errors:"
                grep -i "error\|fail\|denied" xcodebuild_archive.log | tail -10 || echo "No obvious errors in archive log"
              fi
              
              echo "=== Checking iOS build directory ==="
              ls -la build/ios/ 2>/dev/null || echo "build/ios/ directory does not exist"
              
              exit 1
            fi
          fi
          
          # Verify the IPA file is valid
          echo "=== IPA File Details ==="
          ls -lh "$IPA_FILE"
          file "$IPA_FILE"
          
          # Set environment variable for next steps
          echo "IPA_PATH=$IPA_FILE" >> $GITHUB_ENV
          echo "✅ IPA verification completed successfully"
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ${{ env.IPA_PATH }}
          retention-days: 7

  distribute-ios:
    needs: build-ios
    runs-on: ubuntu-latest
    steps:
      - name: Download IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-app
          path: ./
      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la ./
          
          # The IPA should be named flutter_riverpod_tutorial.ipa based on your project
          if [ -f "flutter_riverpod_tutorial.ipa" ]; then
            echo "✅ Found flutter_riverpod_tutorial.ipa"
            mv flutter_riverpod_tutorial.ipa app-release.ipa
          else
            # Fallback: look for any IPA file
            IPA_FILES=(*.ipa)
            if [ -f "${IPA_FILES[0]}" ]; then
              echo "✅ Found IPA file: ${IPA_FILES[0]}, renaming to app-release.ipa"
              mv "${IPA_FILES[0]}" app-release.ipa
            else
              echo "❌ No IPA file found in downloaded artifacts"
              echo "Available files:"
              ls -la ./
              exit 1
            fi
          fi
          
          echo "Final file check:"
          ls -la ./app-release.ipa
          file app-release.ipa
      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: testers
          file: app-release.ipa
          releaseNotes: "Automatic build from GitHub Actions (Commit: ${{ github.sha }})"
